<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'CieloLink\\' => array($vendorDir . '/edson-nascimento/cielo-link-php/src/CieloLink'),
);
