<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit53de5ae9b12f907ac396f10925cf72bf
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CieloLink\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CieloLink\\' => 
        array (
            0 => __DIR__ . '/..' . '/cielo/cielo-link-php/src/CieloLink',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit53de5ae9b12f907ac396f10925cf72bf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit53de5ae9b12f907ac396f10925cf72bf::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit53de5ae9b12f907ac396f10925cf72bf::$classMap;

        }, null, ClassLoader::class);
    }
}
